[package]
name = "tic-tac-toe"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <you@example.com>"]

[dependencies]
bevy = { version = "0.17", default-features = true }

[profile.dev]
opt-level = 1

[profile.release]
opt-level = "z"
codegen-units = 1
lto = true
panic = "abort"
strip = true
