name: Rust CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  build:
    name: Build / Test / Lint
    strategy:
      fail-fast: false
      matrix:
        include:
          # For main branch pushes: build on all platforms
          - os: ubuntu-latest
            name: Linux
            if: github.event_name == 'push' && github.ref == 'refs/heads/main'
          - os: windows-latest
            name: Windows
            if: github.event_name == 'push' && github.ref == 'refs/heads/main'
          - os: macos-latest
            name: macOS
            if: github.event_name == 'push' && github.ref == 'refs/heads/main'
          # For pull requests: only build on Linux
          - os: ubuntu-latest
            name: Linux
            if: github.event_name == 'pull_request'

    runs-on: ${{ matrix.os }}
    if: ${{ matrix.if }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true

      - name: Install Linux deps for Bevy wgpu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libasound2-dev libudev-dev pkg-config libxkbcommon-dev libwayland-dev libx11-dev libxcursor-dev \
            libxi-dev libxrandr-dev libxinerama-dev

      - name: fmt check
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: build
        run: cargo build --locked --verbose

      - name: test
        run: cargo test --all --verbose
